# Development override file
# Provides development-specific configurations

services:
  webapp-find-artek:
    container_name: webapp-find-artek-dev
    build:
      dockerfile: Dockerfile.develop
    env_file:
      - .dev.env  # Development environment variables
    environment:
      MYSQL_HOST: find-artek-mariadb-service
      ENABLE_CRON: ${ENABLE_CRON:-false}
      THUMBNAIL_HEIGHT: ${THUMBNAIL_HEIGHT:-400}
    ports:
      - "8098:8099"
    command: bash -c 'cd /app && python manage.py runserver 0.0.0.0:8099 --settings find_artek.development_settings'

  find-artek-mariadb-service:
    container_name: fa-mariadb-service-dev
    env_file:
      - .dev.env

  find-artek-phpmyadmin-service:
    container_name: fa-phpmyadmin-service-dev
    env_file:
      - .dev.env
    ports:
      - "6002:80"
    environment:
      PMA_HOST: find-artek-mariadb-service

volumes:
  staticfiles_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../00_static_data/find_artek_static/staticfiles
  media_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../00_static_data/find_artek_static/media
  find-artek-mariadb-data:
    name: find-artek-mariadb-dev
    external: true
