# Base Docker Compose file
# Defines the abstract services and their relationships.
# Environment-specific details are provided in override files.

services:
  webapp-find-artek:
    restart: always
    build:
      context: .
      # Dockerfile is specified in override files
    # env_file is specified in override files to use correct .env file
    volumes:
      # Abstract volumes for static and media files.
      # The 'ro' flag ensures staticfiles are read-only for the app.
      - staticfiles_data:/mnt/shared-project-data/staticfiles:ro
      - media_data:/mnt/shared-project-data/media:rw
    networks:
      - docker_default
    stdin_open: true
    tty: true

  find-artek-mariadb-service:
    restart: always
    image: mariadb:11.2
    # env_file is specified in override files to use correct .env file
    volumes:
      - find-artek-mariadb-data:/var/lib/mysql
      - ./docker/mariadb-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docker_default

  find-artek-phpmyadmin-service:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "6001:80" # Default for prod, can be overridden
    # env_file is specified in override files to use correct .env file
    environment:
      PMA_HOST: find-artek-mariadb-service
    volumes:
      - ./docker/phpmyadmin-service/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - docker_default

volumes:
  staticfiles_data:
    # Driver and options are defined in override files
  media_data:
    # Driver and options are defined in override files
  find-artek-mariadb-data:
    # For production, this will be a managed volume.
    # For development, it can be external to reuse data.

networks:
  docker_default:
    external: true
