# Generated by Django 4.2 on 2023-08-15 10:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appendenciesship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, choices=[('PHOTO', 'Photo'), ('SAMPLE', 'Sample'), ('BOREHOLE', 'Borehole'), ('GEOPHYSICAL DATA', 'Geophysical data'), ('FIELD MEASUREMENT', 'Field measurement'), ('LAB MEASUREMENT', 'Lab measurement'), ('RESOURCE', 'Resource'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=65535)),
                ('comment', models.TextField(blank=True, max_length=65535)),
                ('points', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('lines', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('polys', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('pos_quality', models.CharField(blank=True, choices=[('Approximate', 'Approximate'), ('GPS (phase)', 'GPS (phase)'), ('GPS (code)', 'GPS (code)'), ('Unknown', 'Unknown')], default='Unknown', max_length=30)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Current'), (10, 'Created'), (20, 'Changed'), (40, 'Rejected'), (50, 'Obsolete')], default=10)),
            ],
            options={
                'permissions': (('edit_own_feature', 'Can edit own featuress'), ('delete_own_feature', 'Can delete own features')),
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('original_URL', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(max_length=1000, upload_to=publications.models.get_file_path)),
                ('description', models.TextField(blank=True, max_length=65535)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('original_URL', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(upload_to=publications.models.get_image_path)),
                ('caption', models.TextField(max_length=1000)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keywordship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('quality', models.SmallIntegerField(choices=[(0, 'Current'), (10, 'Created'), (20, 'Changed'), (40, 'Rejected'), (50, 'Obsolete')], default=10)),
                ('first_relaxed', models.CharField(blank=True, max_length=10)),
                ('last_relaxed', models.CharField(blank=True, max_length=100)),
                ('first', models.CharField(blank=True, max_length=100)),
                ('middle', models.CharField(blank=True, max_length=100)),
                ('prelast', models.CharField(blank=True, max_length=100)),
                ('last', models.CharField(blank=True, max_length=100)),
                ('lineage', models.CharField(blank=True, max_length=100)),
                ('pre_titulation', models.CharField(blank=True, max_length=100)),
                ('post_titulation', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('initials', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=512)),
                ('department', models.CharField(blank=True, max_length=512)),
                ('address_1', models.CharField(blank=True, max_length=512)),
                ('address_2', models.CharField(blank=True, max_length=512)),
                ('zip_code', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=512)),
                ('cell_phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('homepage', models.URLField(blank=True)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_own_person', 'Can edit own person'), ('delete_own_person', 'Can delete own person')),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('key', models.CharField(blank=True, max_length=100)),
                ('booktitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('crossref', models.CharField(blank=True, max_length=255)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('month', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=255)),
                ('ISBN', models.CharField(blank=True, max_length=255)),
                ('ISBN13', models.CharField(blank=True, max_length=255)),
                ('ISSN', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True, max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('howpublished', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('timestamp', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Current'), (10, 'Created'), (20, 'Changed'), (40, 'Rejected'), (50, 'Obsolete')], default=10)),
            ],
            options={
                'permissions': (('edit_own_publication', 'Can edit own publications'), ('delete_own_publication', 'Can delete own publications'), ('verify_publication', 'Can verify publications')),
            },
        ),
        migrations.CreateModel(
            name='PubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('req_fields', models.CharField(blank=True, max_length=200)),
                ('opt_fields', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='URLObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('URL', models.URLField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('linktext', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topicship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationURLObjectship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.urlobject')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='URLs',
            field=models.ManyToManyField(blank=True, default=None, through='publications.PublicationURLObjectship', to='publications.urlobject'),
        ),
        migrations.AddField(
            model_name='publication',
            name='appendices',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_appendices', through='publications.Appendenciesship', to='publications.fileobject'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_author', through='publications.Authorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_editor', through='publications.Editorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.fileobject'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.journal'),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_keywords',
            field=models.ManyToManyField(blank=True, default=None, through='publications.Keywordship', to='publications.keyword'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_topics',
            field=models.ManyToManyField(blank=True, default=None, through='publications.Topicship', to='publications.topic'),
        ),
        migrations.AddField(
            model_name='publication',
            name='supervisors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_supervisor', through='publications.Supervisorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.pubtype'),
        ),
        migrations.AddField(
            model_name='keywordship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.CreateModel(
            name='ImageObjectship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.feature')),
                ('imageobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.imageobject')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='URLs',
            field=models.ManyToManyField(blank=True, to='publications.urlobject'),
        ),
        migrations.AddField(
            model_name='feature',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='files',
            field=models.ManyToManyField(blank=True, to='publications.fileobject'),
        ),
        migrations.AddField(
            model_name='feature',
            name='images',
            field=models.ManyToManyField(blank=True, through='publications.ImageObjectship', to='publications.imageobject'),
        ),
        migrations.AddField(
            model_name='feature',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='publications',
            field=models.ManyToManyField(blank=True, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='editorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person'),
        ),
        migrations.AddField(
            model_name='editorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='appendenciesship',
            name='fileobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.fileobject'),
        ),
        migrations.AddField(
            model_name='appendenciesship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.CreateModel(
            name='AddPubFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibtexfield', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publication')),
            ],
        ),
    ]
