FROM httpd:2.4

LABEL maintainer="Victor Reipur <victor.reipur@gmail.com>"

##################### LOCALE #####################

# Add these lines after the LABEL directive to set the locale
RUN apt-get update && apt-get install -y locales && \
    sed -i -e 's/# da_DK.UTF-8 UTF-8/da_DK.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG da_DK.UTF-8
ENV LANGUAGE da_DK.UTF-8
ENV LC_ALL da_DK.UTF-8

##################### LOCALE #####################



# TODO
# 2023-08-06 14:54:33 AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message
# 2023-08-06 14:54:33 AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.31.0.6. Set the 'ServerName' directive globally to suppress this message






RUN a2enmod proxy proxy_http

# make conatainer keep running
CMD ["httpd -D FOREGROUND"]

