FROM httpd:2.4

LABEL maintainer="Victor Reipur <victor.reipur@gmail.com>"

##################### LOCALE #####################

# Add these lines after the LABEL directive to set the locale
RUN apt-get update && apt-get install -y locales && \
    sed -i -e 's/# da_DK.UTF-8 UTF-8/da_DK.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG da_DK.UTF-8
ENV LANGUAGE da_DK.UTF-8
ENV LC_ALL da_DK.UTF-8

##################### LOCALE #####################

RUN apt update && apt install -y git iputils-ping
