# .devcontainer override file
# Provides configurations for VS Code Dev Container
# This file extends docker-compose.yml and docker-compose.develop.yml

services:
  webapp-find-artek:
    container_name: webapp-find-artek-devcon
    volumes:
      # Abstract volumes for static and media files.
      # The 'rw' flag ensures staticfiles are read-write for devcontainer.
      - staticfiles_data:/mnt/shared-project-data/staticfiles:rw
      # Mount source code for live editing (current project only)
      - .:/workspace:cached
    working_dir: /workspace/app-main
    environment:
      MYSQL_HOST: find-artek-mariadb-service
      # Override Django project location to use mounted code
      DJANGO_PROJECT_DIR: "/workspace/app-main"
    command: sleep infinity # Keep container running for dev
    # Override the ports to avoid conflicts
    ports:
      - "8100:8099"  # Use different port for dev container

  find-artek-mariadb-service:
    container_name: fa-mariadb-service-devcon

  find-artek-phpmyadmin-service:
    container_name: fa-phpmyadmin-service-devcon
    # Override port to avoid conflicts
    ports:
      - "6002:80"
  

  