# Generated by Django 4.1.4 on 2023-03-02 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Current'), (10, 'Created'), (20, 'Changed'), (40, 'Rejected'), (50, 'Obsolete')], default=10)),
                ('first_relaxed', models.CharField(blank=True, max_length=10)),
                ('last_relaxed', models.CharField(blank=True, max_length=100)),
                ('first', models.CharField(blank=True, max_length=100)),
                ('middle', models.CharField(blank=True, max_length=100)),
                ('prelast', models.CharField(blank=True, max_length=100)),
                ('last', models.CharField(blank=True, max_length=100)),
                ('lineage', models.CharField(blank=True, max_length=100)),
                ('pre_titulation', models.CharField(blank=True, max_length=100)),
                ('post_titulation', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('initials', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=512)),
                ('department', models.CharField(blank=True, max_length=512)),
                ('address_1', models.CharField(blank=True, max_length=512)),
                ('address_2', models.CharField(blank=True, max_length=512)),
                ('zip_code', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=512)),
                ('cell_phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('homepage', models.URLField(blank=True)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_own_person', 'Can edit own person'), ('delete_own_person', 'Can delete own person')),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('booktitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('crossref', models.CharField(blank=True, max_length=255)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('month', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('DOI', models.CharField(blank=True, max_length=255)),
                ('ISBN', models.CharField(blank=True, max_length=255)),
                ('ISBN13', models.CharField(blank=True, max_length=255)),
                ('ISSN', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True, max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('howpublished', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('timestamp', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Current'), (10, 'Created'), (20, 'Changed'), (40, 'Rejected'), (50, 'Obsolete')], default=10)),
                ('author', models.ManyToManyField(blank=True, default=None, related_name='publication_authors', through='publications.Authorship', to='publications.person')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ManyToManyField(blank=True, default=None, related_name='publication_editors', through='publications.Editorship', to='publications.person')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_own_publication', 'Can edit own publications'), ('delete_own_publication', 'Can delete own publications'), ('verify_publication', 'Can verify publications')),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_own_test', 'Can edit own test'), ('delete_own_test', 'Can delete own test')),
            },
        ),
        migrations.CreateModel(
            name='Supervisorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.IntegerField(default=None, null=True)),
                ('exact_match', models.BooleanField(default=False)),
                ('multiple_match', models.BooleanField(default=False)),
                ('relaxed_match', models.BooleanField(default=False)),
                ('match_string', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='supervisor',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_supervisors', through='publications.Supervisorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='editorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person'),
        ),
        migrations.AddField(
            model_name='editorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.person'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
