# Generated by Django 4.1.4 on 2023-03-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlobject',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlobject',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
