# Generated by Django 4.1.4 on 2023-03-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
