# Generated by Django 4.1.4 on 2023-03-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_remove_publication_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=100)),
            ],
        ),
    ]
