# Generated by Django 4.1.4 on 2023-03-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.journal'),
        ),
    ]
