# Generated by Django 4.1.4 on 2023-03-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('required_fields', models.CharField(blank=True, max_length=200)),
                ('optional_fields', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publications.publicationtype'),
        ),
    ]
