# Generated by Django 4.1.4 on 2023-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publicationtype_publication_publication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_topic',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='publications.publicationtopic'),
        ),
    ]
