# Generated by Django 4.1.4 on 2023-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_publicationtopic_publication_publication_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_topic',
            field=models.ManyToManyField(blank=True, default=None, to='publications.publicationtopic'),
        ),
    ]
