# Generated by Django 4.1.4 on 2023-03-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_alter_publication_publication_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_topic',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications_authored', through='publications.Authorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications_edited', through='publications.Editorship', to='publications.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_topics',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications', to='publications.publicationtopic'),
        ),
        migrations.AddField(
            model_name='publication',
            name='supervisors',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications_supervised', through='publications.Supervisorship', to='publications.person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.journal'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.publicationtype'),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications', to='publications.publicationkeyword'),
        ),
    ]
