# Generated by Django 4.1.4 on 2023-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publicationkeyword_remove_publication_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications', to='publications.publicationkeyword'),
        ),
    ]
