# Generated by Django 4.1.4 on 2023-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_fileobject_publication_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='file',
            new_name='file_object',
        ),
        migrations.AddField(
            model_name='publication',
            name='appendices',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publication_appendices', to='publications.fileobject'),
        ),
    ]
