# Generated by Django 4.1.4 on 2023-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_rename_file_publication_file_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='appendices',
            field=models.ManyToManyField(blank=True, default=None, related_name='publication_appendices', to='publications.fileobject'),
        ),
    ]
