# Generated by Django 4.1.4 on 2023-03-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_imageobject_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPubFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibtexfield', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publication')),
            ],
        ),
    ]
