# Generated by Django 4.1.4 on 2023-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_alter_publication_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='appendices',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publication_appendices', to='publications.fileobject'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications_authored', through='publications.Authorship', to='publications.person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications_edited', through='publications.Editorship', to='publications.person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications', to='publications.publicationkeyword'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_topics',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications', to='publications.publicationtopic'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publications_urls',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='publications.urlobject'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='supervisors',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications_supervised', through='publications.Supervisorship', to='publications.person'),
        ),
    ]
